### ISSUE TITLE
Doc - missing info about filename and place to save the template

### ISSUE THREAD

**Issue by Huluvu424242** [JanGatting/GitCommitMessage#19]
Hello,

i am looking in the README for the filename of the template but i does not found him. 
You have an  file GitCommitMessage.template in the project root.
Contains this file the commit message template?
Will be intellij use it if i commit an delta?

Thanks 

Thomas

**Comment by kekru** [comment]
Hi Thomas,
yes the GitCommitMessage.template contains the template and should be in the project root.  
IntelliJ will create this file, when you edit the template in IntelliJ's commit dialog, but you can store it there manually, too.

**Comment by Huluvu424242** [comment]
Thanks
